Repository buildo/bento-design-system, pull requests merged in 2022-11, with the labels that each got.

#420 Avoid including react-dom in the bundle
  packages/bento-design-system/package.json
Labels: waiting for merge, chore

#426 Add detection of circular dependencies
  ci/pipeline.yml
  ci/tasks/circular-deps.yml
  package.json
  packages/bento-design-system/package.json
  packages/bento-design-system/src/BentoConfigContext.tsx
  packages/bento-design-system/src/DateField/Day.tsx
  packages/bento-design-system/src/Feedback/Feedback.tsx
  packages/bento-design-system/src/List/Config.ts
  packages/bento-design-system/src/List/InternalList.tsx
  packages/bento-design-system/src/List/ListItem.tsx
  packages/bento-design-system/src/SelectField/components.tsx
  packages/bento-design-system/src/react-input-mask.d.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
  pnpm-lock.yaml
  turbo.json
Labels: WIP, chore

#433 Fix the alignment of labels in `fill-parent` Tabs
  packages/bento-design-system/src/Tabs/Tabs.tsx
Labels: bug, waiting for merge

#432 Uniform the `color` prop of typography components
  packages/bento-design-system/src/AreaLoader/AreaLoader.tsx
  packages/bento-design-system/src/Checkbox/InternalCheckbox.tsx
  packages/bento-design-system/src/DateField/DateField.tsx
  packages/bento-design-system/src/Disclosure/Disclosure.tsx
  packages/bento-design-system/src/List/ListItem.tsx
  packages/bento-design-system/src/NumberInput/NumberInput.tsx
  packages/bento-design-system/src/RadioGroupField/RadioGroupField.tsx
  packages/bento-design-system/src/SearchBar/SearchBar.tsx
  packages/bento-design-system/src/SelectField/components.tsx
  packages/bento-design-system/src/Switch/Switch.tsx
  packages/bento-design-system/src/TextArea/TextArea.tsx
  packages/bento-design-system/src/TextField/TextField.tsx
  packages/bento-design-system/src/TimeField/DateSegment.tsx
  packages/bento-design-system/src/Toast/Toast.tsx
  packages/bento-design-system/src/Typography/Body/Body.css.ts
  packages/bento-design-system/src/Typography/Body/Body.tsx
  packages/bento-design-system/src/Typography/Display/Display.css.ts
  packages/bento-design-system/src/Typography/Display/Display.tsx
  packages/bento-design-system/src/Typography/Headline/Headline.css.ts
  packages/bento-design-system/src/Typography/Headline/Headline.tsx
  packages/bento-design-system/src/Typography/Label/Label.css.ts
  packages/bento-design-system/src/Typography/Label/Label.tsx
  packages/bento-design-system/src/Typography/Title/Title.css.ts
  packages/bento-design-system/src/Typography/Title/Title.tsx
  packages/bento-design-system/src/Typography/TypographyColor.ts
Labels: in review, breaking

#434 Improve underline configuration
  packages/bento-design-system/src/Navigation/Config.ts
  packages/bento-design-system/src/Navigation/Navigation.tsx
  packages/bento-design-system/src/Tabs/Config.ts
  packages/bento-design-system/src/Tabs/Tabs.tsx
  packages/bento-design-system/src/util/atoms.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: in review, breaking

#443 Add Title as valid typography for Feedback title
  packages/bento-design-system/src/Feedback/Config.ts
  packages/bento-design-system/src/Feedback/Feedback.tsx
Labels: waiting for merge

#445 Remove stray textTransform: uppercase
  packages/bento-design-system/src/Button/Button.css.ts
Labels: bug

#446 Add baseline option for alignY
  packages/bento-design-system/src/util/align.ts
  packages/bento-design-system/src/util/atoms.ts
  packages/bento-design-system/src/util/collapsible.ts
  packages/storybook/stories/Layout/Columns.stories.tsx
Labels: WIP

#379 #368: Force Tooltip position
  packages/bento-design-system/src/CheckboxField/CheckboxField.tsx
  packages/bento-design-system/src/Field/Config.ts
  packages/bento-design-system/src/Field/Field.tsx
  packages/bento-design-system/src/Field/FieldProps.ts
  packages/bento-design-system/src/ReadOnlyField/ReadOnlyField.tsx
  packages/bento-design-system/src/SelectField/SelectField.tsx
  packages/bento-design-system/src/Table/Config.ts
  packages/bento-design-system/src/Table/Table.tsx
  packages/bento-design-system/src/Table/cells.tsx
  packages/bento-design-system/src/TimeField/TimeField.tsx
  packages/bento-design-system/src/Tooltip/Tooltip.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Tooltip.stories.tsx
Labels: in review

#452 Add copy functionality to ReadOnlyField
  packages/bento-design-system/src/BentoConfig.ts
  packages/bento-design-system/src/Icons/IconCopyLight.tsx
  packages/bento-design-system/src/Icons/index.ts
  packages/bento-design-system/src/ReadOnlyField/Config.ts
  packages/bento-design-system/src/ReadOnlyField/ReadOnlyField.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/ReadonlyField.stories.tsx
Labels: waiting for merge

#455 Honor bento config for MultiValue message in SelectField
  packages/bento-design-system/src/SelectField/SelectField.tsx
Labels: bug, WIP

#456 Make FieldProp name and onBlur optional
  packages/bento-design-system/src/Field/FieldProps.ts
  packages/bento-design-system/src/ReadOnlyField/ReadOnlyField.tsx
  packages/bento-design-system/src/useComponentsShowcase.tsx
  packages/storybook/stories/Components/Form.stories.tsx
  packages/storybook/stories/Components/Table.stories.tsx
  packages/website/src/snippets/Components/CheckboxField.tsx
  packages/website/src/snippets/Components/DateField.tsx
  packages/website/src/snippets/Components/Form.tsx
  packages/website/src/snippets/Components/NumberField.tsx
  packages/website/src/snippets/Components/RadioGroupField.tsx
  packages/website/src/snippets/Components/SelectField.tsx
  packages/website/src/snippets/Components/SliderField.tsx
  packages/website/src/snippets/Components/Switch.tsx
  packages/website/src/snippets/Components/TextArea.tsx
  packages/website/src/snippets/Components/TextField.tsx
  packages/website/src/snippets/Components/TimeField.tsx
  packages/website/src/snippets/Form/fields.tsx
Labels: in review

#453 Add FileUploaderField component
  packages/bento-design-system/package.json
  packages/bento-design-system/src/BentoConfig.ts
  packages/bento-design-system/src/FileUploaderField/Config.ts
  packages/bento-design-system/src/FileUploaderField/FileUploaderField.css.ts
  packages/bento-design-system/src/FileUploaderField/FileUploaderField.tsx
  packages/bento-design-system/src/createBentoComponents.ts
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/FileUploaderField.stories.tsx
  packages/storybook/stories/index.tsx
  packages/website/docs/04-Components/FileUploaderField.mdx
  packages/website/src/snippets/Components/FileUploaderField.tsx
  packages/website/src/snippets/index.tsx
  pnpm-lock.yaml
Labels: WIP
