Repository buildo/bento-design-system, pull requests merged in 2022-12, with the labels that each got.

#461 Allow passing Children to CheckboxField label
  packages/bento-design-system/src/CheckboxField/CheckboxField.tsx
  packages/storybook/stories/Components/CheckboxField.stories.tsx
Labels: bug, in review

#462 Remove IsMulti type parameter from SelectField
  packages/bento-design-system/src/SelectField/SelectField.tsx
  packages/bento-design-system/src/SelectField/components.tsx
  packages/storybook/stories/Components/Form.stories.tsx
  packages/website/src/snippets/Form/fields.tsx
Labels: bug, waiting for merge

#442 Basic charts
  packages/bento-design-system/package.json
  packages/bento-design-system/src/BentoConfig.ts
  packages/bento-design-system/src/Charts/BarChart/BarChart.tsx
  packages/bento-design-system/src/Charts/ChartProps.ts
  packages/bento-design-system/src/Charts/Config.ts
  packages/bento-design-system/src/Charts/DonutChart/DonutChart.tsx
  packages/bento-design-system/src/Charts/Legend/Legend.tsx
  packages/bento-design-system/src/Charts/LineChart/LineChart.tsx
  packages/bento-design-system/src/Charts/Tooltip/Tooltip.tsx
  packages/bento-design-system/src/Charts/index.ts
  packages/bento-design-system/src/charts.ts
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/src/util/atoms.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/package.json
  packages/storybook/stories/Components/Charts/BarChart.stories.tsx
  packages/storybook/stories/Components/Charts/DonutChart.stories.tsx
  packages/storybook/stories/Components/Charts/LineChart.stories.tsx
  packages/storybook/stories/index.tsx
  packages/website/docs/04-Components/BarChart.mdx
  packages/website/docs/04-Components/DonutChart.mdx
  packages/website/docs/04-Components/LineChart.mdx
  packages/website/src/snippets/Components/BarChart.tsx
  packages/website/src/snippets/Components/DonutChart.tsx
  packages/website/src/snippets/Components/LineChart.tsx
  pnpm-lock.yaml
Labels: in review

#474 Show rightAccessory in ReadOnlyField
  packages/bento-design-system/src/ReadOnlyField/ReadOnlyField.tsx
  packages/storybook/stories/Components/ReadonlyField.stories.tsx
Labels: bug, waiting for merge

#478 ButtonLink Avoid passing "icon" to the link component
  packages/bento-design-system/src/Button/ButtonLink.tsx
Labels: bug, WIP

#476 #472: Add support for units of measurement on BarChart component
  packages/bento-design-system/src/Charts/BarChart/BarChart.tsx
  packages/bento-design-system/src/Charts/DonutChart/DonutChart.tsx
  packages/bento-design-system/src/Charts/LineChart/LineChart.tsx
  packages/bento-design-system/src/Charts/Tooltip/Tooltip.tsx
  packages/bento-design-system/src/Charts/ValueFormatter.ts
  packages/bento-design-system/src/Charts/index.ts
  packages/storybook/stories/Components/Charts/BarChart.stories.tsx
  packages/storybook/stories/Components/Charts/DonutChart.stories.tsx
  packages/storybook/stories/Components/Charts/LineChart.stories.tsx
Labels: waiting for merge

#482 #477: Make charts Tooltip follow Card style
  packages/bento-design-system/src/Charts/BarChart/BarChart.tsx
  packages/bento-design-system/src/Charts/DonutChart/DonutChart.tsx
  packages/bento-design-system/src/Charts/LineChart/LineChart.tsx
  packages/bento-design-system/src/Charts/Tooltip/Tooltip.tsx
Labels: in review

#486 #485: Expose Chart resources to allow creating custom charts
  packages/bento-design-system/src/Charts/BarChart/BarChart.tsx
  packages/bento-design-system/src/Charts/DonutChart/DonutChart.tsx
  packages/bento-design-system/src/Charts/Legend/Legend.tsx
  packages/bento-design-system/src/Charts/LineChart/LineChart.tsx
  packages/bento-design-system/src/Charts/Tooltip/Tooltip.tsx
  packages/bento-design-system/src/Charts/index.ts
  packages/bento-design-system/src/Charts/useChart.tsx
  packages/storybook/stories/Components/Charts/BarChart.stories.tsx
  packages/storybook/stories/Components/Charts/CustomChart.stories.tsx
  packages/storybook/stories/index.tsx
Labels: in review

#489 #488: Add missing outline to DatePicker
  packages/bento-design-system/src/DateField/DateField.css.ts
Labels: waiting for merge
