Repository buildo/bento-design-system, pull requests merged in 2022-04, with the labels that each got.

#140 #4780394: Disclosure: add trailing icon
  packages/bento-design-system/src/Disclosure/Config.ts
  packages/bento-design-system/src/Disclosure/createDisclosure.tsx
  packages/bento-design-system/src/DisclosureGroup/Config.ts
  packages/bento-design-system/src/DisclosureGroup/createDisclosureGroup.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Disclosure.stories.tsx
  packages/storybook/stories/Components/DisclosureGroup.stories.tsx
Labels: waiting for merge, breaking

#144 Fix outline atoms
  packages/bento-design-system/src/util/atoms.ts
Labels: waiting for merge

#143 Remove TextChildren DSL
  packages/bento-design-system/src/Banner/createBanner.tsx
  packages/bento-design-system/src/BentoConfig.ts
  packages/bento-design-system/src/BentoProvider.tsx
  packages/bento-design-system/src/Breadcrumb/createBreadcrumb.tsx
  packages/bento-design-system/src/Button/ButtonLink.tsx
  packages/bento-design-system/src/Checkbox/createCheckbox.tsx
  packages/bento-design-system/src/CheckboxField/createCheckboxField.tsx
  packages/bento-design-system/src/CheckboxGroupField/createCheckboxGroupField.tsx
  packages/bento-design-system/src/Feedback/createFeedback.tsx
  packages/bento-design-system/src/Field/FieldProps.ts
  packages/bento-design-system/src/Form/Form.tsx
  packages/bento-design-system/src/Form/FormSection.tsx
  packages/bento-design-system/src/Link/Config.ts
  packages/bento-design-system/src/Link/Link.css.ts
  packages/bento-design-system/src/Link/Link.tsx
  packages/bento-design-system/src/List/createListItem.tsx
  packages/bento-design-system/src/Navigation/createNavigation.tsx
  packages/bento-design-system/src/SelectField/components.tsx
  packages/bento-design-system/src/Switch/createSwitch.tsx
  packages/bento-design-system/src/Table/cells.tsx
  packages/bento-design-system/src/Toast/createToast.tsx
  packages/bento-design-system/src/Tooltip/Tooltip.tsx
  packages/bento-design-system/src/Typography/Body/Body.tsx
  packages/bento-design-system/src/Typography/Label/Label.tsx
  packages/bento-design-system/src/createBentoComponents.ts
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/src/util/TextChildren.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/bento-design-system/src/util/link.tsx
  packages/bento-design-system/test/useTextChildrenToChildren.test.tsx
  packages/storybook/stories/Components/Link.stories.tsx
Labels: waiting for merge, breaking

#145 Allow children in Link
  packages/bento-design-system/src/Link/Link.tsx
  packages/storybook/stories/Components/Link.stories.tsx
Labels: waiting for merge

#146 Add more color options to Label and Body
  packages/bento-design-system/src/Typography/Body/Body.css.ts
  packages/bento-design-system/src/Typography/Body/Body.tsx
  packages/bento-design-system/src/Typography/Label/Label.css.ts
  packages/bento-design-system/src/Typography/Label/Label.tsx
Labels: waiting for merge

#147 #3696376: Update all Configurations
  packages/bento-design-system/src/Actions/Config.ts
  packages/bento-design-system/src/Actions/createActions.tsx
  packages/bento-design-system/src/Avatar/Config.ts
  packages/bento-design-system/src/Avatar/createAvatar.tsx
  packages/bento-design-system/src/Banner/Banner.css.ts
  packages/bento-design-system/src/Banner/Config.ts
  packages/bento-design-system/src/Banner/createBanner.tsx
  packages/bento-design-system/src/BentoConfig.ts
  packages/bento-design-system/src/Card/Config.ts
  packages/bento-design-system/src/Card/createCard.tsx
  packages/bento-design-system/src/Chip/Chip.css.ts
  packages/bento-design-system/src/Chip/Config.ts
  packages/bento-design-system/src/Chip/createChip.tsx
  packages/bento-design-system/src/Disclosure/Config.ts
  packages/bento-design-system/src/Disclosure/createDisclosure.tsx
  packages/bento-design-system/src/DisclosureGroup/Config.ts
  packages/bento-design-system/src/DisclosureGroup/createDisclosureGroup.tsx
  packages/bento-design-system/src/Divider/Config.ts
  packages/bento-design-system/src/Feedback/Config.ts
  packages/bento-design-system/src/Feedback/createFeedback.tsx
  packages/bento-design-system/src/Field/Config.ts
  packages/bento-design-system/src/Field/createField.tsx
  packages/bento-design-system/src/Form/Config.ts
  packages/bento-design-system/src/Form/Form.tsx
  packages/bento-design-system/src/Icons/IconInfo.tsx
  packages/bento-design-system/src/Icons/IconSpinner.tsx
  packages/bento-design-system/src/Icons/index.ts
  packages/bento-design-system/src/InlineLoader/Config.ts
  packages/bento-design-system/src/InlineLoader/InlineLoader.tsx
  packages/bento-design-system/src/List/Config.ts
  packages/bento-design-system/src/List/createListItem.tsx
  packages/bento-design-system/src/Menu/createMenu.tsx
  packages/bento-design-system/src/Modal/Config.ts
  packages/bento-design-system/src/Modal/Modal.css.ts
  packages/bento-design-system/src/Modal/createModal.tsx
  packages/bento-design-system/src/ProgressBar/Config.ts
  packages/bento-design-system/src/ProgressBar/createProgressBar.tsx
  packages/bento-design-system/src/SearchBar/Config.ts
  packages/bento-design-system/src/SearchBar/createSearchBar.tsx
  packages/bento-design-system/src/Toast/Config.ts
  packages/bento-design-system/src/Toast/Toast.css.ts
  packages/bento-design-system/src/Toast/createToastInternal.tsx
  packages/bento-design-system/src/Tooltip/Config.ts
  packages/bento-design-system/src/Tooltip/Tooltip.tsx
  packages/bento-design-system/src/createBentoComponents.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Card.stories.tsx
  packages/storybook/stories/Components/Menu.stories.tsx
  packages/storybook/stories/theme.css.ts
Labels: waiting for merge

#151 #4853823: FunctionComponent in configs doesn't work well with Object.Partial / OptionalDeep from ts-toolbelt
  packages/bento-design-system/src/Avatar/Config.ts
  packages/bento-design-system/src/Avatar/createAvatar.tsx
  packages/bento-design-system/src/Banner/Config.ts
  packages/bento-design-system/src/Banner/createBanner.tsx
  packages/bento-design-system/src/Breadcrumb/Config.ts
  packages/bento-design-system/src/Breadcrumb/createBreadcrumb.tsx
  packages/bento-design-system/src/Chip/Config.ts
  packages/bento-design-system/src/Disclosure/Config.ts
  packages/bento-design-system/src/Disclosure/createDisclosure.tsx
  packages/bento-design-system/src/Field/Config.ts
  packages/bento-design-system/src/InlineLoader/Config.ts
  packages/bento-design-system/src/Modal/Config.ts
  packages/bento-design-system/src/SearchBar/Config.ts
  packages/bento-design-system/src/SearchBar/createSearchBar.tsx
  packages/bento-design-system/src/Stepper/Config.ts
  packages/bento-design-system/src/Toast/Config.ts
Labels: waiting for merge

#152 Showcase: render AreaLoader in an absolute div instead of an iframe
  packages/bento-design-system/src/createUseComponentsShowcase.tsx
Labels: waiting for merge

#150 #4820492: Slider should allow to drag with a different granularity
  packages/bento-design-system/src/SliderField/createSliderField.tsx
  packages/storybook/stories/Components/SliderField.stories.tsx
Labels: in review

#154 #3087366: Select List - Fix
  packages/bento-design-system/src/List/ListItem.css.ts
  packages/bento-design-system/src/List/createListItem.tsx
  packages/bento-design-system/src/SelectField/components.tsx
  packages/bento-design-system/src/SelectField/createSelectField.tsx
Labels: waiting for merge

#153 #4822507: Implement the vertical divider and make the dividers configurable
  packages/bento-design-system/src/BentoConfig.ts
  packages/bento-design-system/src/Divider/Config.ts
  packages/bento-design-system/src/Divider/Divider.css.ts
  packages/bento-design-system/src/Divider/Divider.tsx
  packages/bento-design-system/src/createBentoComponents.ts
  packages/bento-design-system/src/createUseComponentsShowcase.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/DecorativeDivider.stories.tsx
  packages/storybook/stories/index.tsx
Labels: in review

#155 Improve storybook build
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/tsup.config.ts
  packages/storybook/.storybook/main.js
  packages/storybook/babel.config.js
  packages/storybook/package.json
  packages/storybook/stories/Components/Card.stories.tsx
  packages/storybook/stories/theme.css.ts
  packages/storybook/stories/util.tsx
  pnpm-lock.yaml
Labels: in review

#156 Default theme
  packages/bento-design-system/src/SelectField/SelectField.css.ts
  packages/bento-design-system/src/SelectField/components.tsx
  packages/bento-design-system/src/defaultTheme.css.ts
  packages/bento-design-system/src/defaultTheme.ts
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/tsup.config.ts
  packages/storybook/stories/index.tsx
  packages/storybook/stories/theme.css.ts
  pnpm-lock.yaml
Labels: waiting for merge

#158 Setup documentation website
  package.json
  packages/bento-design-system/package.json
  packages/bento-design-system/src/Button/Config.ts
  packages/bento-design-system/src/createBentoComponents.ts
  packages/bento-design-system/src/defaultTheme.ts
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/tsup.config.ts
  packages/storybook/stories/fonts.css
  packages/storybook/stories/index.tsx
  packages/website/docs/Components/Button.mdx
  packages/website/docs/Components/_ComponentDoc.mdx
  packages/website/docs/Guides/layout.mdx
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/src/components/Canvas.tsx
  packages/website/src/components/PropTable.tsx
  packages/website/src/css/custom.css
  packages/website/src/snippets/Components/Button.tsx
  packages/website/src/snippets/Layout/ColumnsAlignY.tsx
  packages/website/src/snippets/Layout/ColumnsCollapseBelow.tsx
  packages/website/src/snippets/Layout/ColumnsContentSizedColumn.tsx
  packages/website/src/snippets/Layout/ColumnsResponsiveReverse.tsx
  packages/website/src/snippets/Layout/ColumnsThreeColumn.tsx
  packages/website/src/snippets/Layout/ColumnsTwoColumn.tsx
  packages/website/src/snippets/Layout/ContentBlockAlignCenter.tsx
  packages/website/src/snippets/Layout/ContentBlockAlignDefault.tsx
  packages/website/src/snippets/Layout/InlineAlign.tsx
  packages/website/src/snippets/Layout/InlineAlignResponsive.tsx
  packages/website/src/snippets/Layout/InlineBasic.tsx
  packages/website/src/snippets/Layout/InlineCollapseBelow.tsx
  packages/website/src/snippets/Layout/InlineReverse.tsx
  packages/website/src/snippets/Layout/InsetAllAxis.tsx
  packages/website/src/snippets/Layout/InsetHorizontalAndVertical.tsx
  packages/website/src/snippets/Layout/StackAlign.tsx
  packages/website/src/snippets/Layout/StackAlignResponsive.tsx
  packages/website/src/snippets/Layout/StackBasic.tsx
  packages/website/src/snippets/Layout/StackDividers.tsx
  packages/website/src/snippets/Layout/TilesResponsive.tsx
  packages/website/src/snippets/Layout/TilesThreeColumn.tsx
  packages/website/src/snippets/formatMessage.ts
  packages/website/src/snippets/index.tsx
  packages/website/src/theme/ReactLiveScope/index.js
  pnpm-lock.yaml
Labels: in review

#157 use friendlier names for CSS variables
  packages/bento-design-system/src/vars.css.ts
Labels: waiting for merge

#159 Add PackageManagerCommand
  packages/website/docs/intro.mdx
  packages/website/src/components/PackageManagerCommand.tsx
Labels: waiting for merge

#164 Some love for the homepage
  packages/website/docusaurus.config.js
  packages/website/src/components/HomepageFeatures.tsx
  packages/website/src/pages/index.tsx
Labels: waiting for merge

#165 Make LocalizedString type configurable via module augmentation
  packages/bento-design-system/src/IconButton/createIconButton.tsx
  packages/bento-design-system/src/Modal/createModal.tsx
  packages/bento-design-system/src/NumberField/createNumberField.tsx
  packages/bento-design-system/src/NumberInput/createNumberInput.tsx
  packages/bento-design-system/src/SearchBar/createSearchBar.tsx
  packages/bento-design-system/src/Table/cells.tsx
  packages/bento-design-system/src/Table/tableColumn.tsx
  packages/bento-design-system/src/TextField/createTextField.tsx
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/src/util/ConfigurableTypes.ts
  packages/bento-design-system/src/util/LocalizedString.ts
  packages/bento-design-system/test/tsconfig.json
  packages/bento-design-system/test/type-overrides/LocalizedString.tsx
  packages/bento-design-system/test/type-overrides/bento.d.ts
  packages/storybook/stories/bento.d.ts
  packages/website/docs/Advanced/strict-localization.md
Labels: in review, breaking

#163 Review of docs intro
  packages/website/docs/intro.mdx
Labels: in review

#161 Docs intro
  packages/website/docs/intro.mdx
  pnpm-lock.yaml
Labels: in review

#167 Try to fix Canvas rendering in production builds
  packages/website/src/components/Canvas.tsx
  packages/website/tsconfig.json
Labels: WIP

#168 Fix Canvas, again
  packages/website/babel.config.js
  packages/website/src/components/Canvas.tsx
Labels: WIP

#166 add component Props doc
  packages/website/docs/Components/Button.mdx
  packages/website/docusaurus.config.js
Labels: waiting for merge

#170 Add external links to ComponentDoc
  packages/website/docs/Components/Button.mdx
  packages/website/docs/Components/_ComponentDoc.mdx
  packages/website/package.json
  packages/website/src/components/ExternalLinkCard.module.css
  packages/website/src/components/ExternalLinkCard.tsx
  packages/website/static/img/github_dark.svg
  packages/website/static/img/github_light.svg
  packages/website/static/img/storybook.svg
  packages/website/static/img/zeroheight.png
  pnpm-lock.yaml
Labels: waiting for merge

#171 Review Customization
  packages/website/docs/Customization.md
  packages/website/docs/sprinkles-setup.md
  packages/website/src/snippets/Customization/Box.tsx
  packages/website/src/snippets/Customization/BoxStatusProperties.tsx
Labels: waiting for merge

#169 Docs components
  packages/bento-design-system/src/Button/createButton.tsx
  packages/website/docs/Components/Actions.mdx
  packages/website/docs/Components/AreaLoader.mdx
  packages/website/docs/Components/Avatar.mdx
  packages/website/docs/Components/Banner.mdx
  packages/website/docs/Components/Breadcrumb.mdx
  packages/website/docs/Components/Button.mdx
  packages/website/docs/Components/Card.mdx
  packages/website/docs/Components/CheckboxField.mdx
  packages/website/docs/Components/Chip.mdx
  packages/website/docs/Components/Disclosure.mdx
  packages/website/docs/Components/Divider.mdx
  packages/website/docs/Components/Feedback.mdx
  packages/website/docs/Components/Form.mdx
  packages/website/docs/Components/InlineLoader.mdx
  packages/website/docs/Components/List.mdx
  packages/website/docs/Components/Menu.mdx
  packages/website/docs/Components/Modal.mdx
  packages/website/docs/Components/Navigation.mdx
  packages/website/docs/Components/ProgressBar.mdx
  packages/website/docs/Components/RadioGroupField.mdx
  packages/website/docs/Components/SearchBar.mdx
  packages/website/docs/Components/SliderField.mdx
  packages/website/docs/Components/Stepper.mdx
  packages/website/docs/Components/Switch.mdx
  packages/website/docs/Components/Table.mdx
  packages/website/docs/Components/Tabs.mdx
  packages/website/docs/Components/TextField.mdx
  packages/website/docs/Components/Toast.mdx
  packages/website/docs/Components/Tooltip.mdx
  packages/website/docs/Components/_ComponentDoc.mdx
  packages/website/docusaurus.config.js
  packages/website/src/components/ComponentHeader.tsx
Labels: waiting for merge

#172 reorder docs pages + minor fixes
  packages/website/docs/01-intro.mdx
  packages/website/docs/02-Getting Started/01-quick-start.mdx
  packages/website/docs/02-Getting Started/02-atomic-styles.mdx
  packages/website/docs/02-Getting Started/03-project-setup.mdx
  packages/website/docs/03-Customization/01-theming.mdx
  packages/website/docs/03-Customization/02-configuration.mdx
  packages/website/docs/03-Customization/03-atoms-augmentation.mdx
  packages/website/docs/03-Customization/index.md
  packages/website/docs/04-Components/Actions.mdx
  packages/website/docs/04-Components/AreaLoader.mdx
  packages/website/docs/04-Components/Avatar.mdx
  packages/website/docs/04-Components/Banner.mdx
  packages/website/docs/04-Components/Breadcrumb.mdx
  packages/website/docs/04-Components/Button.mdx
  packages/website/docs/04-Components/Card.mdx
  packages/website/docs/04-Components/CheckboxField.mdx
  packages/website/docs/04-Components/Chip.mdx
  packages/website/docs/04-Components/Disclosure.mdx
  packages/website/docs/04-Components/Divider.mdx
  packages/website/docs/04-Components/Feedback.mdx
  packages/website/docs/04-Components/Form.mdx
  packages/website/docs/04-Components/InlineLoader.mdx
  packages/website/docs/04-Components/List.mdx
  packages/website/docs/04-Components/Menu.mdx
  packages/website/docs/04-Components/Modal.mdx
  packages/website/docs/04-Components/Navigation.mdx
  packages/website/docs/04-Components/ProgressBar.mdx
  packages/website/docs/04-Components/RadioGroupField.mdx
  packages/website/docs/04-Components/SearchBar.mdx
  packages/website/docs/04-Components/SliderField.mdx
  packages/website/docs/04-Components/Stepper.mdx
  packages/website/docs/04-Components/Switch.mdx
  packages/website/docs/04-Components/Table.mdx
  packages/website/docs/04-Components/Tabs.mdx
  packages/website/docs/04-Components/TextField.mdx
  packages/website/docs/04-Components/Toast.mdx
  packages/website/docs/04-Components/Tooltip.mdx
  packages/website/docs/04-Components/_ComponentDoc.mdx
  packages/website/docs/05-Guides/layout.mdx
  packages/website/docs/06-Advanced/strict-localization.mdx
  packages/website/docs/Customization.md
Labels: in review

#175 Add Form guide
  packages/website/docs/02-Getting Started/01-quick-start.mdx
  packages/website/docs/05-Guides/form.mdx
  packages/website/docs/05-Guides/layout.mdx
  packages/website/src/components/Canvas.tsx
  packages/website/src/snippets/Form/Basic.tsx
  packages/website/src/snippets/Form/BasicWithCancelButton.tsx
  packages/website/src/snippets/Form/BasicWithSubmitButton.tsx
  packages/website/src/snippets/Form/BasicWithTitleAndDescription.tsx
  packages/website/src/snippets/Form/CustomFieldWidths.tsx
  packages/website/src/snippets/Form/MultipleSections.tsx
  packages/website/src/snippets/Form/fields.tsx
  packages/website/src/snippets/defaultMessages.ts
  packages/website/src/snippets/index.tsx
Labels: waiting for merge

#176 remove config table, expand enum types
  packages/website/docs/04-Components/_ComponentDoc.mdx
  packages/website/docusaurus.config.js
  packages/website/src/components/PropTable.tsx
  packages/website/src/components/useComponentMetadata.ts
Labels: waiting for merge

#178 Add playroom link and make code blocks collapsible
  packages/website/docs/04-Components/_ComponentDoc.mdx
  packages/website/package.json
  packages/website/src/components/Canvas.module.css
  packages/website/src/components/Canvas.tsx
  pnpm-lock.yaml
Labels: waiting for merge

#180 #3129679: Allow to configure the selected locale in DesignSystemProvider
  packages/bento-design-system/src/BentoProvider.tsx
Labels: waiting for merge
