Repository buildo/bento-design-system, pull requests merged in 2022-09, with the labels that each got.

#369 Export FieldProps
  packages/bento-design-system/src/Field/Field.tsx
Labels: waiting for merge

#359 #354: Menu: allow sub-menus
  packages/bento-design-system/src/List/List.tsx
  packages/bento-design-system/src/List/ListItem.tsx
  packages/bento-design-system/src/Menu/Config.ts
  packages/bento-design-system/src/Menu/Menu.tsx
  packages/bento-design-system/src/Menu/MenuList.tsx
  packages/bento-design-system/src/Menu/MenuProps.ts
  packages/bento-design-system/src/Menu/NestedMenu.tsx
  packages/bento-design-system/src/Menu/NestedMenuListItem.tsx
  packages/bento-design-system/src/Popover/Popover.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Menu.stories.tsx
Labels: in review

#377 fix import example
  packages/website/docs/02-Getting Started/03-project-structure.mdx
Labels: waiting for merge

#380 #378: Inline props not resolved correctly
  packages/bento-design-system/src/Box/Box.tsx
  packages/bento-design-system/src/Layout/Inline.tsx
  packages/bento-design-system/src/Layout/Stack.tsx
  packages/bento-design-system/src/Typography/Title/Title.tsx
Labels: waiting for merge

#382 Make @vanilla-extract/css a dependency
  packages/bento-design-system/package.json
  pnpm-lock.yaml
Labels: bug, WIP

#383 #381: Certain navigation components don't trigger their action
  packages/bento-design-system/src/Box/Box.tsx
Labels: waiting for merge
