Repository buildo/bento-design-system, pull requests merged in 2022-05, with the labels that each got.

#131 #3692685: Implement DatePicker
  packages/bento-design-system/package.json
  packages/bento-design-system/src/BentoConfig.ts
  packages/bento-design-system/src/DateField/Calendar.tsx
  packages/bento-design-system/src/DateField/CalendarHeader.tsx
  packages/bento-design-system/src/DateField/Config.ts
  packages/bento-design-system/src/DateField/DateField.css.ts
  packages/bento-design-system/src/DateField/Day.tsx
  packages/bento-design-system/src/DateField/Input.tsx
  packages/bento-design-system/src/DateField/Selector.tsx
  packages/bento-design-system/src/DateField/createDateField.tsx
  packages/bento-design-system/src/DefaultMessagesContext.tsx
  packages/bento-design-system/src/Field/Field.css.ts
  packages/bento-design-system/src/Field/createFormFields.tsx
  packages/bento-design-system/src/Icons/IconChevronLeft.tsx
  packages/bento-design-system/src/Icons/index.ts
  packages/bento-design-system/src/Layout/Tiles.css.ts
  packages/bento-design-system/src/Layout/createTiles.tsx
  packages/bento-design-system/src/Menu/Menu.css.ts
  packages/bento-design-system/src/Menu/createMenu.tsx
  packages/bento-design-system/src/createBentoComponents.ts
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/src/internal/index.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/bento-design-system/test/util/defaultMessages.ts
  packages/storybook/package.json
  packages/storybook/stories/Components/DateField.stories.tsx
  packages/storybook/stories/defaultMessages.ts
  packages/storybook/stories/index.tsx
  packages/website/docs/04-Components/DateField.mdx
  packages/website/src/snippets/Components/DateField.tsx
  packages/website/src/snippets/defaultMessages.ts
  packages/website/src/snippets/index.tsx
  pnpm-lock.yaml
  turbo.json
Labels: in review

#179 #4956598: Menu - Voci active e inactive dello stesso colore
  packages/bento-design-system/src/Navigation/Navigation.css.ts
Labels: waiting for merge

#184 fix datepicker
  packages/bento-design-system/src/DateField/Selector.tsx
Labels: waiting for merge

#181 Project structure docs
  packages/website/docs/02-Getting Started/03-project-setup.mdx
  packages/website/docs/02-Getting Started/03-project-structure.mdx
  pnpm-workspace.yaml
Labels: waiting for merge

#186 customize docusaurus theme
  packages/website/docs/01-intro.mdx
  packages/website/docusaurus.config.js
  packages/website/src/components/Canvas.module.css
  packages/website/src/components/HomepageFeatures.module.css
  packages/website/src/components/HomepageFeatures.tsx
  packages/website/src/css/custom.css
  packages/website/src/pages/index.module.css
  packages/website/src/pages/index.tsx
  packages/website/static/img/CoverDark.svg
  packages/website/static/img/CoverLight.svg
  packages/website/static/img/Hoso.svg
  packages/website/static/img/Rice.svg
  packages/website/static/img/Salmon.svg
  packages/website/static/img/undraw_docusaurus_mountain.svg
  packages/website/static/img/undraw_docusaurus_react.svg
  packages/website/static/img/undraw_docusaurus_tree.svg
Labels: waiting for merge

#187 Intro
  packages/website/docs/01-intro.mdx
Labels: documentation, waiting for merge

#188 Fix links in docs
  packages/website/src/components/ExternalLinkCard.module.css
Labels: documentation, waiting for merge

#191 Review of #190
  packages/bento-design-system/src/Chip/Chip.css.ts
  packages/bento-design-system/src/Chip/createChip.tsx
  packages/storybook/stories/Components/Chip.stories.tsx
Labels: waiting for merge

#192 #4972850: Slider - add configurations for thumb and trail sizes
  packages/bento-design-system/src/Slider/Config.ts
  packages/bento-design-system/src/Slider/Slider.css.ts
  packages/bento-design-system/src/Slider/createSlider.tsx
  packages/bento-design-system/src/SliderField/createSliderField.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/SliderField.stories.tsx
Labels: waiting for merge

#197 Fix website edit url
  packages/website/docusaurus.config.js
Labels: WIP

#195 #4862669: Banner, Modal: separate padding config into paddingX/paddingY
  packages/bento-design-system/src/Banner/Config.ts
  packages/bento-design-system/src/Banner/createBanner.tsx
  packages/bento-design-system/src/Modal/Config.ts
  packages/bento-design-system/src/Modal/createModal.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: waiting for merge, breaking

#198 #4980202: Table - add default sorting
  packages/bento-design-system/src/Table/createTable.tsx
  packages/storybook/stories/Components/Table.stories.tsx
Labels: waiting for merge

#193 #4965437: Field - add negative icon to error messages
  packages/bento-design-system/src/Field/createField.tsx
  packages/bento-design-system/src/Icons/IconNegative.tsx
  packages/bento-design-system/src/Icons/IconWarning.tsx
Labels: waiting for merge

#194 #4972335: Trailing switch
  packages/bento-design-system/src/Switch/createSwitch.tsx
  packages/storybook/stories/Components/Switch.stories.tsx
Labels: waiting for merge

#199 #4965975: Fix playroom autocomplete
  packages/bento-design-system/playroom.config.js
Labels: waiting for merge

#200 Fix a weird glitch with background: cover on iOS
  packages/website/src/pages/index.module.css
Labels: documentation, waiting for merge

#201 Fix input hint icon color
  packages/bento-design-system/src/Field/createField.tsx
Labels: bug, in review

#202 Fix Table section header colors
  packages/bento-design-system/src/Table/createTable.tsx
Labels: bug, waiting for merge

#205 Add missing imports in MDX
  packages/website/docs/02-Getting Started/01-quick-start.mdx
  packages/website/docs/02-Getting Started/03-project-structure.mdx
Labels: WIP

#208 Add Algolia search
  packages/website/docusaurus.config.js
  packages/website/src/css/custom.css
Labels: waiting for merge

#204 Support stateful components and strip TypeScript syntax in Playroom
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/src/components/Canvas.tsx
  pnpm-lock.yaml
Labels: documentation, waiting for merge

#209 Add ContentWithSidebar component
  packages/bento-design-system/src/BentoProvider.tsx
  packages/bento-design-system/src/ContentWithSidebar/createContentWithSidebar.tsx
  packages/bento-design-system/src/createBentoComponents.ts
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/src/util/atoms.ts
  packages/storybook/stories/Components/ContentWithSidebar.stories.tsx
  packages/storybook/stories/index.tsx
  packages/website/docs/04-Components/ContentWithSidebar.mdx
  packages/website/src/snippets/Components/ContentWithSidebar.tsx
  packages/website/src/snippets/index.tsx
Labels: waiting for merge

#211 Add rightAccessory to Tabs tab
  packages/bento-design-system/src/Tabs/createTabs.tsx
  packages/storybook/stories/Components/Tabs/FolderTabs.stories.tsx
  packages/storybook/stories/index.tsx
Labels: in review

#213 #5017558: Remove body default margin
  packages/bento-design-system/src/global.css.ts
Labels: waiting for merge

#215 Allow Children in List labels
  packages/bento-design-system/src/List/createListComponents.tsx
  packages/bento-design-system/src/List/createListItem.tsx
  packages/storybook/stories/Components/List.stories.tsx
Labels: WIP

#218 export Stepper Step component
  packages/bento-design-system/src/Stepper/createStepper.tsx
  packages/bento-design-system/src/createBentoComponents.ts
Labels: waiting for merge

#219 Add icon to LinkButton + fix onPress type
  packages/bento-design-system/src/Button/ButtonLink.tsx
  packages/bento-design-system/src/Button/createButton.tsx
  packages/storybook/stories/Components/ButtonLink.stories.tsx
Labels: waiting for merge

#220 allow to pass complex Children to StepperStep label
  packages/bento-design-system/src/Stepper/createStepper.tsx
Labels: in review

#223 #5191301: Disclosure title has the same color in level 1 and 2
  packages/bento-design-system/src/Disclosure/createDisclosure.tsx
Labels: in review

#224 #5097621: DateField - date picker grows when there are too many shortcuts
  packages/bento-design-system/src/DateField/Calendar.tsx
  packages/bento-design-system/src/DateField/Config.ts
Labels: waiting for merge

#226 Use border instead of outline for Card, Menu, and Toast
  packages/bento-design-system/src/Card/Card.css.ts
  packages/bento-design-system/src/Menu/Menu.css.ts
  packages/bento-design-system/src/Toast/Toast.css.ts
  packages/bento-design-system/src/util/atoms.ts
Labels: waiting for merge

#227 Add explicit grid-auto-rows: max-content to Table rows
  packages/bento-design-system/src/Table/Table.css.ts
  packages/bento-design-system/src/Table/createTable.tsx
Labels: bug, waiting for merge
