Repository buildo/bento-design-system, pull requests merged in 2022-08, with the labels that each got.

#340 #320: Use official floating-ui dependency instead of fork
  packages/bento-design-system/package.json
  packages/bento-design-system/src/Tooltip/Tooltip.tsx
  pnpm-lock.yaml
Labels: WIP, dependencies

#214 #5038391: Improve Actions error (impacts also Form and Modal)
  packages/bento-design-system/src/Actions/Config.ts
  packages/bento-design-system/src/Actions/createActions.tsx
  packages/bento-design-system/src/Form/Config.ts
  packages/bento-design-system/src/Form/Form.tsx
  packages/bento-design-system/src/Modal/Config.ts
  packages/bento-design-system/src/Modal/createModal.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Actions/Actions.stories.tsx
  packages/storybook/stories/Components/Actions/ActionsLeftAligned.stories.tsx
  packages/storybook/stories/Components/Actions/ActionsSpaceBetween.stories.tsx
  packages/storybook/stories/index.tsx
  packages/storybook/stories/util.tsx
Labels: waiting for merge

#330 #319: Use `{ custom: number }` convention for Illustration size
  packages/bento-design-system/src/Illustrations/IllustrationProps.ts
  packages/bento-design-system/src/Illustrations/svgIllustrationProps.ts
Labels: in review, breaking

#351 #347: SelectionControlGroup: remove paddingY config
  packages/bento-design-system/src/CheckboxGroupField/createCheckboxGroupField.tsx
  packages/bento-design-system/src/Field/Config.ts
  packages/bento-design-system/src/RadioGroupField/createRadioGroupField.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: in review, breaking

#360 Add missing ListItem export
  packages/bento-design-system/src/index.ts
Labels: WIP

#365 Remove ts-toolbelt
  packages/bento-design-system/package.json
  packages/bento-design-system/src/BentoConfig.ts
  packages/bento-design-system/src/Checkbox/Checkbox.tsx
  packages/bento-design-system/src/SearchBar/SearchBar.tsx
  packages/bento-design-system/src/util/AtLeast.ts
  packages/bento-design-system/src/util/ConfigurableTypes.ts
  packages/bento-design-system/src/util/Overwrite.ts
  packages/bento-design-system/src/util/PartialDeep.ts
  pnpm-lock.yaml
Labels: waiting for merge

#366 Remove duplicate FieldProps eport
  packages/bento-design-system/src/Field/Field.tsx
Labels: bug, waiting for merge
