Repository buildo/bento-design-system, pull requests merged in 2022-07, with the labels that each got.

#248 add inverse colors to Title
  packages/bento-design-system/src/Typography/Title/Title.css.ts
  packages/bento-design-system/src/Typography/Title/Title.tsx
Labels: waiting for merge

#250 add DataViz colors to foreground/border colors
  packages/bento-design-system/src/util/atoms.ts
Labels: waiting for merge

#254 Fix borderStyle atoms
  packages/bento-design-system/src/util/atoms.ts
Labels: bug, waiting for merge

#263 Update several dependencies
  package.json
  packages/bento-design-system/package.json
  packages/storybook/package.json
  packages/website/docusaurus.config.js
  packages/website/package.json
  packages/website/src/components/Canvas.tsx
  packages/website/src/components/ComponentHeader.tsx
  packages/website/src/components/PropTable.tsx
  packages/website/src/components/useComponentMetadata.ts
  pnpm-lock.yaml
Labels: WIP, dependencies

#264 Update docusaurus
  packages/website/package.json
  pnpm-lock.yaml
Labels: dependencies

#160 More flexible createBentoComponents
  packages/bento-design-system/src/createBentoComponents.ts
  packages/bento-design-system/test/createBentoComponents.test.ts
  packages/website/docs/03-Customization/02-configuration.mdx
  packages/website/docs/03-Customization/03-atoms-augmentation.mdx
  packages/website/src/snippets/index.tsx
  pnpm-lock.yaml
Labels: in review

#265 Update to React 18 and related dependencies
  package.json
  packages/bento-design-system/package.json
  packages/bento-design-system/src/Table/types.ts
  packages/bento-design-system/src/react-input-mask.d.ts
  packages/bento-design-system/test/IconButton.test.tsx
  packages/bento-design-system/test/useToast.test.tsx
  packages/bento-design-system/test/util/ignoreWarnings.ts
  packages/storybook/package.json
  packages/website/package.json
  pnpm-lock.yaml
Labels: in review

#270 Added required aria props to SearchBar component
  packages/bento-design-system/src/SearchBar/createSearchBar.tsx
  packages/bento-design-system/src/createUseComponentsShowcase.tsx
  packages/storybook/stories/Components/SearchBar.stories.tsx
  packages/website/src/snippets/Components/SearchBar.tsx
Labels: in review, breaking

#271 Add Governance document
  packages/website/docs/Governance/governance.md
  packages/website/docusaurus.config.js
Labels: WIP

#282 #281: Sticky table header and fixed table height
  packages/bento-design-system/src/Table/Table.css.ts
  packages/bento-design-system/src/Table/createTable.tsx
  packages/storybook/stories/Components/Table.stories.tsx
Labels: in review

#273 Add TextArea component
  packages/bento-design-system/src/Field/Field.css.ts
  packages/bento-design-system/src/Field/createFormFields.tsx
  packages/bento-design-system/src/TextArea/createTextArea.tsx
  packages/bento-design-system/src/createBentoComponents.ts
  packages/storybook/stories/Components/TextArea.stories.tsx
  packages/storybook/stories/index.tsx
  packages/website/docs/04-Components/TextArea.mdx
  packages/website/src/snippets/Components/TextArea.tsx
  packages/website/src/snippets/index.tsx
Labels: in review

#288 Added autofocus prop into Modal
  packages/bento-design-system/src/Modal/createModal.tsx
Labels: waiting for merge

#295 Added check on SelectField's value prop
  packages/bento-design-system/src/SelectField/createSelectField.tsx
Labels: bug, in review

#278 Added searchable prop to SelectField
  packages/bento-design-system/src/SelectField/createSelectField.tsx
Labels: in review

#299 #296: Remove ModalContext
  packages/bento-design-system/src/Modal/ModalContext.ts
  packages/bento-design-system/src/Modal/createModal.tsx
  packages/bento-design-system/src/Modal/useModalContext.ts
  packages/bento-design-system/src/index.ts
  pnpm-lock.yaml
Labels: waiting for merge, breaking

#301 #298: Bug: Radio group control background should be Background/Primary
  packages/bento-design-system/src/RadioGroupField/Radio.css.ts
Labels: bug, in review

#300 #293: Add iconSize to Disclosure config
  packages/bento-design-system/src/Disclosure/Config.ts
  packages/bento-design-system/src/Disclosure/createDisclosure.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: waiting for merge

#308 #262: Bug: Tables lose their sorting status when interacting with them
  packages/bento-design-system/src/Table/createTable.tsx
Labels: waiting for merge

#316 Add optional `tooltipContent` to `textWithIcon` and `numberWithIcon` columns
  packages/bento-design-system/src/Table/cells.tsx
  packages/bento-design-system/src/Table/createTable.tsx
  packages/bento-design-system/src/Table/tableColumn.tsx
  packages/bento-design-system/src/createBentoComponents.ts
  packages/storybook/stories/Components/Table.stories.tsx
Labels: WIP

#317 Add sideEffects field to package.json to allow bundlers to treeshake
  packages/bento-design-system/package.json
Labels: WIP, chore

#322 Add SelectField to docs, fix storybook links and cleanup unused imports
  packages/website/docs/04-Components/Actions.mdx
  packages/website/docs/04-Components/AreaLoader.mdx
  packages/website/docs/04-Components/Avatar.mdx
  packages/website/docs/04-Components/Banner.mdx
  packages/website/docs/04-Components/Breadcrumb.mdx
  packages/website/docs/04-Components/Button.mdx
  packages/website/docs/04-Components/Card.mdx
  packages/website/docs/04-Components/Checkbox.mdx
  packages/website/docs/04-Components/CheckboxField.mdx
  packages/website/docs/04-Components/Chip.mdx
  packages/website/docs/04-Components/ContentWithSidebar.mdx
  packages/website/docs/04-Components/DateField.mdx
  packages/website/docs/04-Components/Disclosure.mdx
  packages/website/docs/04-Components/Divider.mdx
  packages/website/docs/04-Components/Feedback.mdx
  packages/website/docs/04-Components/Form.mdx
  packages/website/docs/04-Components/InlineLoader.mdx
  packages/website/docs/04-Components/List.mdx
  packages/website/docs/04-Components/Menu.mdx
  packages/website/docs/04-Components/Modal.mdx
  packages/website/docs/04-Components/Navigation.mdx
  packages/website/docs/04-Components/ProgressBar.mdx
  packages/website/docs/04-Components/RadioGroupField.mdx
  packages/website/docs/04-Components/SearchBar.mdx
  packages/website/docs/04-Components/SelectField.mdx
  packages/website/docs/04-Components/SliderField.mdx
  packages/website/docs/04-Components/Stepper.mdx
  packages/website/docs/04-Components/Switch.mdx
  packages/website/docs/04-Components/Table.mdx
  packages/website/docs/04-Components/Tabs.mdx
  packages/website/docs/04-Components/TextArea.mdx
  packages/website/docs/04-Components/TextField.mdx
  packages/website/docs/04-Components/Toast.mdx
  packages/website/docs/04-Components/Tooltip.mdx
  packages/website/src/snippets/Components/SelectField.tsx
Labels: documentation, WIP

#285 Added show password to password field
  packages/bento-design-system/src/DefaultMessagesContext.tsx
  packages/bento-design-system/src/Field/Config.ts
  packages/bento-design-system/src/Field/createFormFields.tsx
  packages/bento-design-system/src/Icons/IconEye.tsx
  packages/bento-design-system/src/Icons/IconEyeClosed.tsx
  packages/bento-design-system/src/Icons/index.ts
  packages/bento-design-system/src/TextField/createTextField.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/bento-design-system/test/IconButton.test.tsx
  packages/bento-design-system/test/util/defaultMessages.ts
  packages/storybook/stories/Components/Link.stories.tsx
  packages/storybook/stories/defaultMessages.ts
  packages/website/src/snippets/defaultMessages.ts
Labels: in review

#324 Fix website props generation
  packages/website/docusaurus.config.js
Labels: documentation, WIP

#325 Allow @types/react 18 as peer dependencies
  package.json
Labels: WIP, chore

#326 Update @react-aria related dependencies
  packages/bento-design-system/package.json
  pnpm-lock.yaml
Labels: WIP

#313 Improve table sorting example
  packages/bento-design-system/src/Table/createTable.tsx
  packages/storybook/stories/Components/Table.stories.tsx
Labels: waiting for merge

#329 #292: Autofocus on fields
  packages/bento-design-system/src/Checkbox/createInternalCheckbox.tsx
  packages/bento-design-system/src/CheckboxGroupField/createCheckboxGroupField.tsx
  packages/bento-design-system/src/DateField/createDateField.tsx
  packages/bento-design-system/src/Field/FieldProps.ts
  packages/bento-design-system/src/Form/Form.tsx
  packages/bento-design-system/src/NumberField/createNumberField.tsx
  packages/bento-design-system/src/RadioGroupField/createRadioGroupField.tsx
  packages/bento-design-system/src/SearchBar/createSearchBar.tsx
  packages/bento-design-system/src/SelectField/createSelectField.tsx
  packages/bento-design-system/src/Slider/createSlider.tsx
  packages/bento-design-system/src/SliderField/createSliderField.tsx
Labels: waiting for merge
