Repository buildo/bento-design-system, pull requests merged in 2023-05, with the labels that each got.

#595 Upgrade sprinkles to 1.6.0
  packages/bento-design-system/package.json
  packages/bento-design-system/src/sprinkles.ts
  pnpm-lock.yaml
Labels: dependencies

#598 New feedback component
  packages/bento-design-system/src/Banner/Config.ts
  packages/bento-design-system/src/Chip/Config.ts
  packages/bento-design-system/src/Feedback/Config.ts
  packages/bento-design-system/src/Feedback/Feedback.tsx
  packages/bento-design-system/src/Field/Config.ts
  packages/bento-design-system/src/IconButton/Config.ts
  packages/bento-design-system/src/IconButton/IconButton.tsx
  packages/bento-design-system/src/Icons/Icon.css.ts
  packages/bento-design-system/src/Icons/IconProps.ts
  packages/bento-design-system/src/Modal/Config.ts
  packages/bento-design-system/src/ReadOnlyField/Config.ts
  packages/bento-design-system/src/SearchBar/Config.ts
  packages/bento-design-system/src/Table/Config.ts
  packages/bento-design-system/src/Table/Table.tsx
  packages/bento-design-system/src/Toast/Config.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Feedback.stories.tsx
  packages/storybook/stories/index.tsx
Labels: breaking

#603 Fix default hint icon size
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: breaking

#604 [Navigation] Allow to configure Destination's borderRadius and activeVisualElement line width
  packages/bento-design-system/src/Navigation/Config.ts
  packages/bento-design-system/src/Navigation/Navigation.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: breaking

#607 Fix storybook links
  packages/website/docs/01-intro.mdx
  packages/website/src/components/ExternalLinkCard.tsx
Labels: documentation
