Repository buildo/bento-design-system, pull requests merged in 2023-06, with the labels that each got.

#614 Switch from Algolia to local search
  packages/website/docusaurus.config.js
  packages/website/package.json
  pnpm-lock.yaml
Labels: chore

#626 Fix CJS build
  packages/bento-design-system/package.json
Labels: bug

#637 Upgrade tsup and remove patch-esm-ts script
  packages/bento-design-system/package.json
  pnpm-lock.yaml
Labels: chore

#632 Improve doc for LocalizedString + i18next
  packages/website/docs/06-Advanced/strict-localization.mdx
Labels: documentation

#636 Replace jest with vitest
  ci/tasks/test.yml
  packages/bento-design-system/babel-jest.config.cjs
  packages/bento-design-system/jest.config.json
  packages/bento-design-system/package.json
  packages/bento-design-system/test/IconButton.test.tsx
  packages/bento-design-system/test/setupTests.ts
  packages/bento-design-system/test/tsconfig.json
  packages/bento-design-system/test/util/ignoreWarnings.ts
  packages/bento-design-system/vitest.config.ts
  pnpm-lock.yaml
Labels: chore

#463 Make placeholder optional on fields
  packages/bento-design-system/src/NumberField/NumberField.tsx
  packages/bento-design-system/src/ReadOnlyField/ReadOnlyField.tsx
  packages/bento-design-system/src/SearchBar/SearchBar.tsx
  packages/bento-design-system/src/SelectField/SelectField.tsx
  packages/bento-design-system/src/TextArea/TextArea.tsx
  packages/bento-design-system/src/TextField/TextField.tsx
Labels: in review, WIP

#638 Add Pagination docs
  packages/website/docs/01-intro.mdx
  packages/website/docs/04-Components/Pagination.mdx
  packages/website/src/components/ExternalLinkCard.tsx
  packages/website/src/snippets/Components/Pagination.tsx
Labels: documentation

#639 Update all zeroheight slugs
  packages/website/docs/04-Components/Actions.mdx
  packages/website/docs/04-Components/AreaLoader.mdx
  packages/website/docs/04-Components/Avatar.mdx
  packages/website/docs/04-Components/Banner.mdx
  packages/website/docs/04-Components/BarChart.mdx
  packages/website/docs/04-Components/Breadcrumb.mdx
  packages/website/docs/04-Components/Button.mdx
  packages/website/docs/04-Components/Card.mdx
  packages/website/docs/04-Components/Checkbox.mdx
  packages/website/docs/04-Components/CheckboxField.mdx
  packages/website/docs/04-Components/Chip.mdx
  packages/website/docs/04-Components/DateField.mdx
  packages/website/docs/04-Components/Disclosure.mdx
  packages/website/docs/04-Components/DisclosureGroup.mdx
  packages/website/docs/04-Components/Divider.mdx
  packages/website/docs/04-Components/DonutChart.mdx
  packages/website/docs/04-Components/Feedback.mdx
  packages/website/docs/04-Components/Form.mdx
  packages/website/docs/04-Components/InlineLoader.mdx
  packages/website/docs/04-Components/LineChart.mdx
  packages/website/docs/04-Components/List.mdx
  packages/website/docs/04-Components/Menu.mdx
  packages/website/docs/04-Components/Modal.mdx
  packages/website/docs/04-Components/Navigation.mdx
  packages/website/docs/04-Components/NumberField.mdx
  packages/website/docs/04-Components/ProgressBar.mdx
  packages/website/docs/04-Components/RadioGroupField.mdx
  packages/website/docs/04-Components/SearchBar.mdx
  packages/website/docs/04-Components/SelectField.mdx
  packages/website/docs/04-Components/SliderField.mdx
  packages/website/docs/04-Components/Stepper.mdx
  packages/website/docs/04-Components/Switch.mdx
  packages/website/docs/04-Components/Table.mdx
  packages/website/docs/04-Components/Tabs.mdx
  packages/website/docs/04-Components/TextArea.mdx
  packages/website/docs/04-Components/TextField.mdx
  packages/website/docs/04-Components/TimeField.mdx
  packages/website/docs/04-Components/Toast.mdx
  packages/website/docs/04-Components/Tooltip.mdx
Labels: documentation

#640 Add Icons guide
  packages/bento-design-system/src/Icons/svgIconProps.ts
  packages/storybook/package.json
  packages/storybook/stories/Foundations/Icons.stories.tsx
  packages/website/docs/05-Guides/icons.mdx
  packages/website/package.json
  packages/website/src/components/Canvas.tsx
  packages/website/src/snippets/Icons/Configuration.tsx
  packages/website/src/snippets/Icons/Phosphor.tsx
  pnpm-lock.yaml
Labels: documentation

#643 Remove unused smooth-release devDep
  packages/bento-design-system/package.json
  pnpm-lock.yaml
Labels: dependencies

#641 Adjust color of highlighted bg
  packages/website/src/css/custom.css
Labels: documentation

#644 Upgrade react-aria dependencies
  packages/bento-design-system/package.json
  pnpm-lock.yaml
Labels: dependencies
