Repository buildo/bento-design-system, pull requests merged in 2023-07, with the labels that each got.

#642 Remove createDefineBentoSprinkles
  package.json
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/src/internal/sprinkles.css.ts
  packages/bento-design-system/src/sprinkles.ts
  packages/bento-design-system/src/util/atoms.ts
  packages/bento-design-system/src/util/conditions.ts
  packages/bento-design-system/src/util/shorthands.ts
  packages/storybook/stories/sprinkles.css.ts
  packages/website/docs/03-Customization/03-atoms-augmentation.mdx
  patches/@vanilla-extract__sprinkles@1.6.0.patch
  pnpm-lock.yaml
Labels: breaking

#645 Drop React 17
  packages/bento-design-system/package.json
  pnpm-lock.yaml
Labels: breaking, dependencies

#658 Improvements to ListItem, Navigation and Pagination
  packages/bento-design-system/src/List/ListItem.css.ts
  packages/bento-design-system/src/Navigation/Config.ts
  packages/bento-design-system/src/Navigation/Navigation.css.ts
  packages/bento-design-system/src/Navigation/Navigation.tsx
  packages/bento-design-system/src/Pagination/Config.ts
  packages/bento-design-system/src/Pagination/Pagination.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Pagination.stories.tsx
Labels: breaking

#671 Remove Checkbox bottom padding
  packages/bento-design-system/src/Checkbox/InternalCheckbox.tsx
Labels: bug
