Repository buildo/bento-design-system, pull requests merged in 2023-01, with the labels that each got.

#498 Make checkbox border radius configurable
  packages/bento-design-system/src/Checkbox/Checkbox.css.ts
  packages/bento-design-system/src/Checkbox/InternalCheckbox.tsx
  packages/bento-design-system/src/Field/Config.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: in review

#502 Allow Body typography for Chip's label
  packages/bento-design-system/src/Chip/Chip.tsx
  packages/bento-design-system/src/Chip/Config.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: in review, breaking

#500 Allow Body typography for Feedback's medium title
  packages/bento-design-system/src/Feedback/Config.ts
  packages/bento-design-system/src/Feedback/Feedback.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: in review, breaking

#501 Input background
  packages/bento-design-system/src/DateField/DateField.tsx
  packages/bento-design-system/src/Field/Config.ts
  packages/bento-design-system/src/Field/Field.css.ts
  packages/bento-design-system/src/Field/utils.ts
  packages/bento-design-system/src/NumberInput/NumberInput.tsx
  packages/bento-design-system/src/SearchBar/SearchBar.tsx
  packages/bento-design-system/src/TextArea/TextArea.tsx
  packages/bento-design-system/src/TextField/TextField.tsx
  packages/bento-design-system/src/TimeField/TimeField.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: in review

#499 Add spacing token 12
  packages/bento-design-system/src/defaultTheme.css.ts
  packages/bento-design-system/src/vars.css.ts
  packages/website/docs/05-Guides/layout.mdx
  packages/website/src/components/SpacingScale.tsx
Labels: waiting for merge

#504 Add 12 value for borderRadius
  packages/bento-design-system/src/util/atoms.ts
Labels: waiting for merge

#506 Fix vertical Divider
  packages/bento-design-system/src/Divider/Divider.css.ts
  packages/bento-design-system/src/createBentoComponents.ts
  packages/storybook/stories/Components/Divider.stories.tsx
  packages/storybook/stories/index.tsx
Labels: bug, waiting for merge

#503 Outline icon button
  packages/bento-design-system/src/Button/Button.css.ts
  packages/bento-design-system/src/IconButton/IconButton.css.ts
  packages/bento-design-system/src/IconButton/IconButton.tsx
  packages/bento-design-system/src/defaultTheme.css.ts
  packages/bento-design-system/src/vars.css.ts
  packages/storybook/stories/Components/IconButton.stories.tsx
Labels: in review, breaking

#507 Allow config of background color for Table's even rows
  packages/bento-design-system/src/Table/Config.ts
  packages/bento-design-system/src/Table/Table.css.ts
  packages/bento-design-system/src/Table/Table.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: waiting for merge

#509 Allow configuring actions size in Modal
  packages/bento-design-system/src/Modal/Config.ts
  packages/bento-design-system/src/Modal/Modal.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: WIP

#510 Allow configuring icon position in Button
  packages/bento-design-system/src/Button/Button.tsx
  packages/bento-design-system/src/Button/Config.ts
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Button.stories.tsx
Labels: WIP

#508 Allow config of cells and headers padding for Table
  packages/bento-design-system/src/Table/Config.ts
  packages/bento-design-system/src/Table/Table.css.ts
  packages/bento-design-system/src/Table/Table.tsx
  packages/bento-design-system/src/Table/cells.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
Labels: in review

#511 Allow separate config of paddingX and paddingY for IconButton
  packages/bento-design-system/src/IconButton/Config.ts
  packages/bento-design-system/src/IconButton/IconButton.tsx
Labels: waiting for merge

#514 Fix arrow position when Tooltip is auto-positioned to the left
  packages/bento-design-system/src/Tooltip/Tooltip.tsx
Labels: bug, waiting for merge

#512 Allow interactive rows on Table
  packages/bento-design-system/src/Table/Config.ts
  packages/bento-design-system/src/Table/Table.css.ts
  packages/bento-design-system/src/Table/Table.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Table.stories.tsx
Labels: in review

#515 Fix hard-coded empty cell padding for Table
  packages/bento-design-system/src/Table/tableColumn.tsx
Labels: waiting for merge

#518 Expand config and props of List/ListItem
  packages/bento-design-system/src/Illustrations/IllustrationProps.ts
  packages/bento-design-system/src/List/Config.ts
  packages/bento-design-system/src/List/InternalList.tsx
  packages/bento-design-system/src/List/List.tsx
  packages/bento-design-system/src/List/ListItem.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/List.stories.tsx
Labels: waiting for merge

#519 Expand modal and chip config
  packages/bento-design-system/src/Chip/Chip.css.ts
  packages/bento-design-system/src/Chip/Chip.tsx
  packages/bento-design-system/src/Chip/Config.ts
  packages/bento-design-system/src/Modal/Config.ts
  packages/bento-design-system/src/Modal/Modal.tsx
  packages/bento-design-system/src/util/defaultConfigs.tsx
  packages/storybook/stories/Components/Chip.stories.tsx
Labels: waiting for merge
