Repository buildo/bento-design-system, pull requests merged in 2023-03, with the labels that each got.

#529 Add support for ESM
  packages/bento-design-system/babel-jest.config.cjs
  packages/bento-design-system/babel.config.cjs
  packages/bento-design-system/jest.config.js
  packages/bento-design-system/jest.config.json
  packages/bento-design-system/jsxShim.ts
  packages/bento-design-system/package.json
  packages/bento-design-system/playroom.config.cjs
  packages/bento-design-system/playroom/FrameComponent.tsx
  packages/bento-design-system/src/BentoConfigContext.tsx
  packages/bento-design-system/src/Box/Box.tsx
  packages/bento-design-system/src/DateField/DateField.tsx
  packages/bento-design-system/src/Layout/Columns.tsx
  packages/bento-design-system/src/Layout/Inline.tsx
  packages/bento-design-system/src/Layout/Stack.tsx
  packages/bento-design-system/src/Layout/Tiles.tsx
  packages/bento-design-system/src/Modal/Modal.tsx
  packages/bento-design-system/src/SelectField/components.tsx
  packages/bento-design-system/src/util/flattenChildren.ts
  packages/bento-design-system/src/util/withBentoConfig.tsx
  packages/bento-design-system/tsup.config.ts
  packages/storybook/stories/index.tsx
  packages/website/docs/02-Getting Started/01-quick-start.mdx
  packages/website/docs/02-Getting Started/03-project-structure.mdx
  packages/website/docs/03-Customization/01-theming.mdx
  packages/website/src/components/HomepageFeatures.tsx
  packages/website/src/css/custom.css
  packages/website/src/pages/index.tsx
  pnpm-lock.yaml
Labels: waiting for merge, breaking

#542 Downgrade sprinkles to v1.4.1 (to solve #540)
  packages/bento-design-system/package.json
  packages/bento-design-system/src/sprinkles.ts
  pnpm-lock.yaml
Labels: waiting for merge

#553 Export default defaultMessages for the English language
  packages/bento-design-system/package.json
  packages/bento-design-system/playroom/FrameComponent.tsx
  packages/bento-design-system/src/TextField/TextField.tsx
  packages/bento-design-system/src/defaultMessages/en.ts
  packages/bento-design-system/test/useToast.test.tsx
  packages/bento-design-system/test/util/defaultMessages.ts
  packages/bento-design-system/tsup.config.ts
  packages/storybook/.storybook/preview.js
  packages/storybook/stories/Components/Toast.stories.tsx
  packages/storybook/stories/Utils/withBentoConfig.stories.tsx
  packages/storybook/stories/defaultMessages.ts
  packages/website/docs/02-Getting Started/01-quick-start.mdx
  packages/website/src/components/Canvas.tsx
  packages/website/src/components/SpacingScale.tsx
Labels: in review, WIP

#548 Better SSR support
  packages/bento-design-system/package.json
  packages/bento-design-system/src/BentoProvider.tsx
  packages/bento-design-system/src/DateField/Calendar.tsx
  packages/bento-design-system/src/Menu/NestedMenu.tsx
  packages/bento-design-system/src/Modal/Modal.tsx
  packages/bento-design-system/src/SelectField/SelectField.tsx
  packages/bento-design-system/src/Tooltip/Tooltip.tsx
  packages/bento-design-system/src/index.ts
  packages/bento-design-system/src/util/createPortal.ts
  packages/bento-design-system/src/util/useCreatePortal.ts
  packages/website/docs/02-Getting Started/04-ssr.mdx
  pnpm-lock.yaml
Labels: in review

#555 Generate .d.cts files alongside .d.ts files.
  packages/bento-design-system/package.json
Labels: waiting for merge

#554 Add alternativeNames and relatedComponents to ComponentDoc
  packages/website/docs/04-Components/Actions.mdx
  packages/website/docs/04-Components/AreaLoader.mdx
  packages/website/docs/04-Components/BarChart.mdx
  packages/website/docs/04-Components/Checkbox.mdx
  packages/website/docs/04-Components/CheckboxField.mdx
  packages/website/docs/04-Components/Disclosure.mdx
  packages/website/docs/04-Components/DisclosureGroup.mdx
  packages/website/docs/04-Components/DonutChart.mdx
  packages/website/docs/04-Components/FileUploaderField.mdx
  packages/website/docs/04-Components/Form.mdx
  packages/website/docs/04-Components/InlineLoader.mdx
  packages/website/docs/04-Components/LineChart.mdx
  packages/website/docs/04-Components/Navigation.mdx
  packages/website/docs/04-Components/NumberField.mdx
  packages/website/docs/04-Components/RadioGroupField.mdx
  packages/website/docs/04-Components/SelectField.mdx
  packages/website/docs/04-Components/SliderField.mdx
  packages/website/docs/04-Components/Switch.mdx
  packages/website/docs/04-Components/Tabs.mdx
  packages/website/docs/04-Components/TextArea.mdx
  packages/website/docs/04-Components/TextField.mdx
  packages/website/docs/04-Components/TimeField.mdx
  packages/website/docs/04-Components/_ComponentDoc.mdx
  packages/website/package.json
  packages/website/src/snippets/index.tsx
  pnpm-lock.yaml
Labels: documentation, in review

#551 Add more form-related props to `Button`. Add onKeyDown and onKeyUp to `TextField` and `TextArea`.
  packages/bento-design-system/package.json
  packages/bento-design-system/src/Button/Button.tsx
  packages/bento-design-system/src/Icons/IconEye.tsx
  packages/bento-design-system/src/Icons/IconEyeClosed.tsx
  packages/bento-design-system/src/TextArea/TextArea.tsx
  packages/bento-design-system/src/TextField/TextField.tsx
  packages/storybook/stories/Components/Form.stories.tsx
  pnpm-lock.yaml
Labels: WIP
